Dependency management
RockefellerArchiveCenter/project_electron pull request #105
Opened 2021-08-24 15:37 UTC by HaSistrunk

Fixes #104 

- Adds dependabot and Travis configs with specified ruby version.
- Adds html-proofer
- Removes gemspec and uses github-pages gem in Gemfile. [Type Theme removed its own use of gemspec](https://github.com/rohanchandra/type-theme/blob/master/Gemfile) in 2019.
- The Jekyll Type Theme used here is not versioned and does not have releases, but a review of the repo commit history does not indicate changes to the theme that are relevant to our implementation.
- Updates config to remove unused plugin and exclude array (based on recommendations from the [Jekyll documentation](https://jekyllrb.com/docs/troubleshooting/#configuration-problems)).

2021-08-30 21:47 UTC, helrond requested changes
A couple of very minor things.

2021-08-30 21:47 UTC, helrond commented on _config.yml
> +# paginate_path: "blog/page:num"
Does it make sense to just delete these lines if we're not using this?

2021-08-30 21:47 UTC, helrond commented on _config.yml
> +# plugins: [jekyll-paginate]
Same here - should we just delete?

2021-08-30 21:47 UTC, helrond commented on _config.yml
>    style: :compressed
```suggestion
  style: compressed
```

2021-08-31 14:00 UTC, helrond approved these changes

2021-08-31 17:15 UTC, p-galligan approved these changes

2021-08-31 17:52 UTC, bonniegee approved these changes

2021-08-31 20:12 UTC, merged